export const ON_LOGIN_REQUEST = "ON_LOGIN_REQUEST";
export const ON_LOGIN_SUCCESS = "ON_LOGIN_SUCCESS";
export const ON_LOGIN_FAILURE = "ON_LOGIN_FAILURE";

export const ON_REGISTER_REQUEST = "ON_REGISTER_REQUEST";
export const ON_REGISTER_SUCCESS = "ON_REGISTER_SUCCESS";
export const ON_REGISTER_FAILURE = "ON_REGISTER_FAILURE";